-- ============================================================
-- DimDim - DDL (Azure SQL Database / T-SQL)
-- Modelo: TB_CLIENTE (1) ---- (N) TB_CONTA
-- ============================================================

IF OBJECT_ID('dbo.TB_CONTA', 'U') IS NOT NULL DROP TABLE dbo.TB_CONTA;
IF OBJECT_ID('dbo.TB_CLIENTE', 'U') IS NOT NULL DROP TABLE dbo.TB_CLIENTE;

CREATE TABLE dbo.TB_CLIENTE (
    ID_CLIENTE   INT IDENTITY(1,1)  NOT NULL,
    NOME         NVARCHAR(100)      NOT NULL,
    CPF          VARCHAR(14)        NOT NULL,
    EMAIL        NVARCHAR(120)      NOT NULL,
    DT_CADASTRO  DATETIME2          NOT NULL
        CONSTRAINT DF_TB_CLIENTE_DT_CADASTRO DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_TB_CLIENTE     PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT UQ_TB_CLIENTE_CPF UNIQUE (CPF)
);

CREATE TABLE dbo.TB_CONTA (
    ID_CONTA      INT IDENTITY(1,1)  NOT NULL,
    ID_CLIENTE    INT                NOT NULL,
    NUMERO_CONTA  VARCHAR(20)        NOT NULL,
    TIPO_CONTA    VARCHAR(20)        NOT NULL,
    SALDO         DECIMAL(15,2)      NOT NULL
        CONSTRAINT DF_TB_CONTA_SALDO DEFAULT 0,
    DT_ABERTURA   DATETIME2          NOT NULL
        CONSTRAINT DF_TB_CONTA_DT_ABERTURA DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_TB_CONTA         PRIMARY KEY (ID_CONTA),
    CONSTRAINT UQ_TB_CONTA_NUMERO  UNIQUE (NUMERO_CONTA),
    CONSTRAINT CK_TB_CONTA_TIPO    CHECK (TIPO_CONTA IN ('CORRENTE', 'POUPANCA')),
    CONSTRAINT FK_TB_CONTA_CLIENTE FOREIGN KEY (ID_CLIENTE)
        REFERENCES dbo.TB_CLIENTE (ID_CLIENTE)
);

CREATE INDEX IX_TB_CONTA_ID_CLIENTE ON dbo.TB_CONTA (ID_CLIENTE);
